apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m5n8obtf6-dotnet-basic
  janus-idp.io/tekton: m5n8obtf6-dotnet-basic
  backstage.io/kubernetes-id: m5n8obtf6-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m5n8obtf6-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
